name: Run Tests on Linux
on:
  push: {}
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        unityVersion:
          - 2021.3.33f1
    steps:
      - name: Generate a license activation file
        run: |
          echo ${{ secrets.UNITY_ALF  }} > Unity_v2021.3.33f1.alf
      - name: Request a Unity license file
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_TOTP_KEY: ${{ secrets.UNITY_TOTP_KEY }}
        run: |
          npm install -g unity-verify-code
          git clone https://github.com/homuler/unity-license-activate.git
          cd unity-license-activate
          npm install
          cd ..
          npm install -g ./unity-license-activate
          unity-license-activate "$UNITY_EMAIL" "$UNITY_PASSWORD" Unity_v2021.3.33f1.alf --authenticator-key "$UNITY_TOTP_KEY"
          ls | xargs -I {} mv {} Unity_lic.ulf
      - name: Upload artifact even on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: png
          path: error.png
      - name: Upload artifact even on failure
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: ulf
          path: Unity_lic.ulf
